apiVersion: v1
kind: Pod
metadata:
  name: app-shell-test-2
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: test-container
    image: "alpine"
    securityContext:
        privileged: true
    command: ["/bin/sh", "-c", "while true; do sleep 10000; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  hostNetwork: true
  dnsPolicy: Default